### ISSUE TITLE
/etc/nginx/nginx.conf 中 没有location /bangumi

### ISSUE THREAD

**Issue by Uzibird** [codysk/BGmi-archive-frontend#2]
- -没错，又是我。

我用 nginx -t 找到了 /etc/nginx/nginx.conf 然而这里面没有 location /bangumi这一项。

（我用的你那个Docker-all-in-one，很好用）

**Comment by codysk** [comment]
那个镜像的话 这里看看
```
/etc/nginx/conf.d/default.conf
```

**Comment by Uzibird** [comment]
阔以了。
但是没有封面
![image](https://user-images.githubusercontent.com/40909658/69046850-e680cf80-0a34-11ea-96af-f760230b3272.png)
而且，播放器在shou'ji'd手机端全屏时候不是横屏那种 有办法吗?

**Comment by codysk** [comment]
封面要手动丢一张图进文件夹

横屏就没有啥好办法了 毕竟只是个网页

**Comment by Uzibird** [comment]
好吧，非常感谢。看了下dplayer官方演示 手机全屏也是竖屏的。。。
